### ISSUE TITLE
run.sh script generates invalid syntax error

### ISSUE THREAD

**Issue by dlabrecq** [RedHatInsights/insights-proxy#19]
The run.sh script generates the following error with python 3.7 on Mac.

```
  File "<string>", line 1
    import os,sys;print os.path.realpath(sys.argv[1])
                         ^
  SyntaxError: invalid syntax
```

If I replace the python command below with `realpath`, it works fine.

https://github.com/RedHatInsights/insights-proxy/blob/master/scripts/run.sh#L13

**Comment by priley86** [comment]
also potentially related for some Mac users...
```
| => SPANDX_CONFIG="/Users/priley/GitHub/insights-proxy/spandx.config.js" bash scripts/run.sh 
scripts/run.sh: line 13: python2: command not found
/Users/priley/GitHub/insights-proxy/spandx.config.js does not point to a file!
```
In my case, the fix was:
```
brew install python2
```
and ensuring
```
export PATH="/usr/local/opt/python@2/libexec/bin:$PATH"
```
was in my path. Hope this also helps others!

**Comment by dlabrecq** [comment]
Yes, my fix was to install python2 as well. Using python2 appears to be a change introduced after I filed this issue.
