### ISSUE TITLE
Mention VirtualBox port forwarding

### ISSUE THREAD

**Issue by Glutexo** [RedHatInsights/insights-proxy#2]
The `run.sh` script spawns a Docker container with the app, that is exposed on port 1337. If your Docker machine runs in VirtualBox, like if using Mac or Windows, it is necessary to set up NAT port forwarding in VirtualBox too. It can be done by a command like this [\[1\]][1]

```
VBoxManage modifyvm "default" --natpf1 "insights,tcp,,1337,,1337"
```

or in the VirtualBox machine settings UI.

I’d put this information to the README as it might not be obvious if you’re not familiar with Docker.

PRs for this:

* [ ] #4

[1]: https://fogstack.wordpress.com/2014/02/09/docker-on-osx-port-forwarding/

**Comment by iphands** [comment]
Hey, can you make a note/section in the README and submit a PR?

**Comment by Glutexo** [comment]
Sure! #4
