### ISSUE TITLE
spandx issue fixed

### ISSUE THREAD

**Issue by mwcz** [RedHatInsights/insights-proxy#24]
There was a longstanding issue with spandx that caused Insights proxy to have to pin to a specific commit.  Just wanted to let you all know that I finally applied the fix Ian submitted.  https://github.com/redhataccess/spandx/pull/87

Can you try updating spandx to version `2.0.0-prerelease.4` and let me know if it works?  All the tests pass, but it would be nice to confirm that the fix worked on your side.

**Comment by cben** [comment]
Friendly ping, I encountered a bug already worked-around in https://github.com/redhataccess/spandx/pull/52. Can insights-proxy move to using upstream master :pray:?

Or at least, pin some commit that's contained in either redhataccess/spandx or RedHatInsights/insights-proxy, currently 0e9ecf0f4173db6d54e61ab559ee90959fa3ca3f is an orphan merge commit on the side :tanabata_tree: 
Currently as a user of insights-proxy, there is no point contributing to either fork of spandx if there is no route to it trickling down...

**Comment by cben** [comment]
@karelhala this can be closed now after #42.

**Comment by karelhala** [comment]
@cben sure thing!

@mwcz thank you for letting us know.
