### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by carlosthe19916** [RedHatInsights/insights-proxy#27]
In Fedora 31 Docker package is no longer available and will not run by default (due to switch to cgroups v2) for more info you can read: https://fedoraproject.org/wiki/Common_F31_bugs#Docker_package_no_longer_available_and_will_not_run_by_default_.28due_to_switch_to_cgroups_v2.29

I saw in the code that recently you removed Podman https://github.com/RedHatInsights/insights-proxy/blob/a3a0b4bbf3ab4348ba893416dd2d85113cea5516/scripts/env.sh#L7

Could we do something to start using Podman again? What was the reason why you removed Podman? I'm using insights-proxy with Podman without any problem (at least nothing that I'm aware of)

**Comment by cben** [comment]
This can be closed now, recent official images support `RUNNER=podman` env var.
